### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by HanyuX** [kaonashi-tyc/Rewrite#2]
Hi Taylor,

The project is interesting. I tried to run it on my computer. However I get an error with the commend: 

> python rewrite.py --mode=train  
>                               --model=medium 
>                               --source_font=path_to_save_bitmap/src.npy 
>                               --target_font=path_to_save_bitmap/trg.npy 
>                               --iter=3000 
>                               --num_examples=2100 
>                               --num_validations=100 --tv=0.0001 
>                               --alpha=0.2 --keep_prob=0.9 
>                               --num_ckpt=10 
>                               --ckpt_dir=path_to_save_checkpoints 
>                               --summary_dir=path_to_save_summaries 
>                               --frame_dir=path_to_save_frames

Do you know why? Thanks.
![image](https://cloud.githubusercontent.com/assets/9690864/23043624/efbdab3c-f46a-11e6-8516-333f038f3643.png)

BTW, some functions you use are deprecated by tf. Maybe you want to update them.

**Comment by kaonashi-tyc** [comment]
I guess it has something to do with update of tensorflow. Which version are you on right now?

I think you can try to change the following code :
`sess.run(tf.initialize_all_variables())`

to 

`sess.run(tf.initialize_all_variables(), feed_dict={phase_train: True})`

to see whether this fix you problem or not

**Comment by HanyuX** [comment]
I works. Thanks.
